### ISSUE TITLE
Switch for port forwarding: invalid args

### ISSUE THREAD

**Issue by chemelli74** [mammuth/ha-fritzbox-tools#100]
After configuring via UI and getting the wifi and port forwarding switches created, I tried to use them.
While wifi work fine, port forwarding gives me an error:

```
2020-05-23 15:18:27 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 284, in <lambda>
    self.connection_type, "AddPortMapping", **self.port_mapping
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 82, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzArgumentError: UPnPError:
errorCode: 402
errorDescription: Invalid Args
```

Simone

**Comment by chemelli74** [comment]
Issue is in the name. Fritzbox allow apostrophe, fritzbox_tools not.

I had a port forwarding rule called "Let's Encrypt".

Simone

**Comment by chemelli74** [comment]
@mammuth did you get time to look into this ?

Thank you,

Simone

**Comment by chemelli74** [comment]
Hi @mammuth , do you plan to check this issue ?

Thanx in advance,

Simone

**Comment by AaronDavidSchneider** [comment]
I don't think that there is any solution. Python uses `"` as well as `'` for strings. The only solution will be to rename your forwarding rule.

**Comment by chemelli74** [comment]
I think the offending char should be escaped like for other languages.

One example: https://cscircles.cemc.uwaterloo.ca/3-comments-literals (paragraph "Escape Sequences")

Simone

**Comment by AaronDavidSchneider** [comment]
Might be possible. I am not sure, if it conflicts with the different string types that are internally used. If you have an idea, feel free to create a PR.

**Comment by chemelli74** [comment]
Will re-open in upstream library

Simone
