### ISSUE TITLE
AttributeError: 'FritzBoxTools' object has no attribute '_unique_id'

### ISSUE THREAD

**Issue by ReneHezser** [mammuth/ha-fritzbox-tools#118]
Hi @AaronDavidSchneider. Autodiscovery is working great. Thanks for adding it with the latest release.
Unfortunately I have this error in my log and entities are not available.
```
2020-10-06 20:05:27 ERROR (MainThread) [custom_components.fritzbox_tools.binary_sensor] Error getting the state from the FRITZ!Box
Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 69, in _async_fetch_update
    status = self.fritzbox_tools.fritzstatus
AttributeError: 'FritzBoxTools' object has no attribute 'fritzstatus'
2020-10-06 20:05:27 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 105, in _create_profile_switches
    if len(fritzbox_tools.profile_switch) > 0:
AttributeError: 'FritzBoxTools' object has no attribute 'profile_switch'
2020-10-06 20:05:27 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up fritzbox_tools platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 52, in unique_id
    return f"{self.fritzbox_tools.unique_id}-{self.entity_id}"
  File "/config/custom_components/fritzbox_tools/__init__.py", line 216, in unique_id
    return self._unique_id
AttributeError: 'FritzBoxTools' object has no attribute '_unique_id'
```
This happens in unconfigured state. Once configured with a profile and restarting HA again, everything is working.

**Comment by AaronDavidSchneider** [comment]
Thanks for the report @ReneHezser! I had the same error with other components as well. Probably, because you did not properly remove fritzbox tools before a restart.
Happens sometimes. Feel free to reopen if it occurs more often to you.
