### ISSUE TITLE
Crash on creating switches in version 1.2.0

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#14]
While it worked in my dev environment, the latest version crashs when setting up the switches in my production HA system.

Probably should have waited before releasing this, because now I'm lacking the time to fix it 🙈 

```
Error while setting up platform fritzbox_tools
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 29, in setup_platform
    FritzBoxPortSwitch(fritzbox_tools, portmap, i)
  File "/config/custom_components/fritzbox_tools/switch.py", line 50, in __init__
    port_mapping["NewProtocol"]
KeyError: 'ip'
```

**Comment by AaronDavidSchneider** [comment]
Can’t look into it right now. My version worked on my homeassistant.

**Comment by AaronDavidSchneider** [comment]
I have found the error. You used a false syntax for the string formatting. Have a look at line 47 in switch.py:
        `self._unique_id = "fritzbox_portforward_{ip}_{port}_{protocol}".format( `
That’s wrong. Should be something like:
        `self._unique_id = "fritzbox_portforward_{}_{:d}_{}".format( `
Have a look at the python docs for reference on string formatting.

**Comment by mammuth** [comment]
> You used a false syntax for the string formatting

Thanks. I now use a proper environment with linting in place. It's a shame that those issues get checked in 🙈
