### ISSUE TITLE
Error while setting up fritzbox_tools platform for binary_sensor

### ISSUE THREAD

**Issue by TheZoker** [mammuth/ha-fritzbox-tools#148]
Since beta version 2021.3.0b0 I get the following issue within my logs for the fritzbox_tools integration:
```
ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up fritzbox_tools platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 29, in async_setup_entry
    async_add_entities([FritzBoxConnectivitySensor(fritzbox_tools)], True)
  File "/config/custom_components/fritzbox_tools/binary_sensor.py", line 41, in __init__
    self.entity_id = ENTITY_ID_FORMAT.format(f"fritzbox_{self.fritzbox_tools.fritzbox_model}_connectivity")
  File "/config/custom_components/fritzbox_tools/__init__.py", line 269, in fritzbox_model
    return self._device_info["model"].replace("FRITZ!Box ", "")
AttributeError: 'FritzBoxTools' object has no attribute '_device_info'
```

**Comment by chemelli74** [comment]
Should be fixe din master, after #159 is merged.

Simone

**Comment by TheZoker** [comment]
Yes can confirm, that this is fixed with that PR

**Comment by mammuth** [comment]
New release `1.15.1`should be available on HACS.
