### ISSUE TITLE
Integration is no longer working - all entities are unavailable

### ISSUE THREAD

**Issue by lweberru** [mammuth/ha-fritzbox-tools#151]
**Fritz Box Tools Version:**
1.14.0

**Home Assistant Info:**

version | core-2021.3.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v7l+
arch | armv7l
timezone | Europe/Berlin

**Fritzbox Version:**
FRITZ!Box 6591 Cable (lgi)
FRITZ!OS: 07.22

**Problem:**
All entities stay unavailable

![image](https://user-images.githubusercontent.com/20902204/110765223-4287ec80-8254-11eb-865c-585a8920e401.png)

**Error Log:**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 137, in _create_wifi_switches
    [FritzBoxWifiSwitch(fritzbox_tools, net, networks[net])],
  File "/config/custom_components/fritzbox_tools/switch.py", line 551, in __init__
    self.entity_id = ENTITY_ID_FORMAT.format(f"fritzbox_{self._fritzbox_tools.fritzbox_model}_{id}")
  File "/config/custom_components/fritzbox_tools/__init__.py", line 269, in fritzbox_model
    return self._device_info["model"].replace("FRITZ!Box ", "")
AttributeError: 'FritzBoxTools' object has no attribute '_device_info'

```

```
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fritzbox_tools/switch.py", line 117, in _create_profile_switches
    if len(fritzbox_tools.profile_switch) > 0:
AttributeError: 'FritzBoxTools' object has no attribute 'profile_switch'
```

**Comment by mammuth** [comment]
Thanks for the report.

Did you try removing + readding the integration?

**Comment by lweberru** [comment]
readding worked - thank you.

**Comment by mammuth** [comment]
Great. Then I'm closing the issue for now, because I doubt that anyone will further investigate it when it's not really an issue.
