### ISSUE TITLE
Version clash with core fritz integration

### ISSUE THREAD

**Issue by mammuth** [mammuth/ha-fritzbox-tools#19]
I think we're getting some issues when installing this integration side-by-side to the core `fritz` integration, because it pins `fritzconnection==0.6.5`, while fritz_tools pins `fritzconnection==0.8.4`.

I guess I just stumbled upon such an issue. Whenever I commented in my device tracker section in my configuration (using the `fritz` integration), HA would not restart with a strange requirements-related error message:
```python
2019-10-11 18:21:25 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall homeassistant.restart (c:c59c8fec10ca49ad851521ba4ab23909)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1242, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 265, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 797, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 154, in async_check_ha_config_file
    hass, p_name
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 44, in async_get_integration_with_requirements
    await async_process_requirements(hass, integration.domain, integration.requirements)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 65, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 45, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3137, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

I think we should make sure to stick to the fritzconnection version that the core uses. So either we create a PR with a tested 0.8.4 upgrade, or we try to downgrade here.

**Comment by AaronDavidSchneider** [comment]
I have came across the same issue. I personally think, that a pull request would be the smoother way. I guess there won’t be conflicts (if just the requirements would be edited), but one would need to test that.

**Comment by mammuth** [comment]
> I personally think, that a pull request would be the smoother way.

Yes, absolutely.

> but one would need to test that.

Exactly. I have no clue whether `fritzconnection` had some breaking changes between those versions. 
However, the `fritz` integration only registers a device tracker, so that's pretty easy to test. 

I mean in the long run, it'd be cool to move all the stuff we've got in `fritzbox_tools` directly into the core anyways. 
However, that means some further work, since the core currently features 5 different integrations around fritzboxes / dect devices which probably should get streamlined once we'd integrate `fritzbox-tools`... :weary:

**Comment by AaronDavidSchneider** [comment]
Yeah that’s true. Would be very nice to move it to the core. There would be some config validation nescessary, etc. It is possible to do. 


Regarding the changes in fritzconnection:
According to https://pypi.org/project/fritzconnection/0.8.4/ 
not much has changed. Only exceptions, ipv6 status and big fixes.

**Comment by mammuth** [comment]
As of the next Home Assistant release (0.101) `fritzconnection` 0.8.4 will be used, so we can probably close this.
