### ISSUE TITLE
Error setting up component - hassio

### ISSUE THREAD

**Issue by benbeton** [mammuth/ha-fritzbox-tools#37]
Great component!

I installed fritzbox-tools with hacs and added the config to my configuration.yaml:

```
fritzbox_tools:
  host: 192.168.10.1
  username: !secret fritzbox_username
  password: !secret fritzbox_password
```

after restarting HA 101.3 (Hassio) I received the following error: 

```
Error during setup of component fritzbox_tools
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 460, in _get_action
    service = self.services[service_name]
KeyError: 'WANCommonIFC:1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/fritzbox_tools/__init__.py", line 79, in async_setup
    device_list=device_list
  File "/config/custom_components/fritzbox_tools/__init__.py", line 109, in __init__
    self.fritzstatus = fc.FritzStatus(fc=self.connection)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzstatus.py", line 58, in __init__
    self.last_bytes_sent = self.bytes_sent
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzstatus.py", line 115, in bytes_sent
    'GetTotalBytesSent')
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 489, in call_action
    action = self._get_action(service_name, action_name)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 462, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WANCommonIFC:1
Connection lost. Reconnecting…
```

any idea what can be wrong?

**Comment by AaronDavidSchneider** [comment]
Thanks for reporting your error @benbeton! Could you please tell us what Fritzbox you are using and how it is connected to the internet?

**Comment by benbeton** [comment]
I’m using a 6490 cable and it’s directly to unitymedia

**Comment by AaronDavidSchneider** [comment]
Thankyou. I have the same setup bot don’t encounter this error. What other Fritzbox related componentes do you use?

**Comment by benbeton** [comment]
I’m only using the component device tracker with the fritzbox

**Comment by mammuth** [comment]
I'm also running HA 101.3 in hassio with the device tracker and fritzbox-tools both being enabled (but with another Fritzbox model and DSL).

So it seems to be no general issue, but rather related to the specific router or the connection type?

**Comment by AaronDavidSchneider** [comment]
@benbeton: Could you please have a look in your fritzbox settings and check both marks of Access Settings in the Home Network in
Home Network- Network- Network Settings are ticked?

**Comment by benbeton** [comment]
that fixed it!
I had only ticket the first box and not "upnp"

I guess that hint would be good on the start page when setting it up.

ty @mammuth and @AaronDavidSchneider for your help!

**Comment by mammuth** [comment]
Glad it's working for you @benbeton!

I just extended the instructions in the readme with these settings 👍
