### ISSUE TITLE
Fritz!Box 7362 SL - guest WiFi switch disabled

### ISSUE THREAD

**Issue by upwindanderl** [mammuth/ha-fritzbox-tools#39]
First! 
Great job, the addon is supercool!

**But is it possible that the model 7362 SL is not featuring the guest wifi feature?**
The switch is grey in my hassio ui

I mean, time ago i used the same model and a homebridge plugin for exact the same (unfortunatly without the port control) feature and it was possible to remote the guest wifi switch

thx a lot

**Comment by mammuth** [comment]
Could you please verify that the following two settings are enabled on your router:

![](https://user-images.githubusercontent.com/3121306/68996105-e5fe0280-0895-11ea-8b0d-1a4487ee6838.png)

You might also try to restart your router and home assistant afterwards.

Otherwise you should post your home assistant log so we can see what's logged by the component.

**Comment by upwindanderl** [comment]
this answer was super fast! :)
everything enabled, i try the restarts after some long download parts ^^

thx meanwhile

**Comment by upwindanderl** [comment]
Ok, 
the restarting in any kind of sort didn't brought the solution.
Also I'm able to enable/disable the Port things, the connection should be ok. 

I'm super sorry
I've no idea how to do get correct LOG 
I tried with a total log by using the setting ui and filtered by hand some Guest Wifi words:
`[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('service_registered', '{"domain": "device_tracker", "service": "see"}', 'LOCAL', '2019-11-26 21:16:00.459602', '2019-11-26 21:24:00.994964', '6997787f03c743f1a32cef3f4c92e166', None)]
(Background on this error at: http://sqlalche.me/e/4xp6)
2019-11-26 22:24:01 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_utc_time_change.<locals>.pattern_time_change_listener(<Event time_c....006556+01:00>) at /usr/src/homeassistant/homeassistant/helpers/event.py:435
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 444, in pattern_time_change_listener
    calculate_next(now)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 428, in calculate_next
    localized_now, matching_seconds, matching_minutes, matching_hours
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 256, in find_next_time_expression_time
    raise ValueError("Cannot find a next time: Time expression never " "matches!")
ValueError: Cannot find a next time: Time expression never matches!
2019-11-26 22:24:01 ERROR (MainThread) [custom_components.fritzbox_tools.switch] Could not get Guest Wifi state
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 460, in _get_action
    service = self.services[service_name]
KeyError: 'WLANConfiguration:3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/switch.py", line 327, in _async_fetch_update
    status = self.fritzbox_tools.connection.call_action('WLANConfiguration:3', 'GetInfo')['NewStatus']
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 489, in call_action
    action = self._get_action(service_name, action_name)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 462, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WLANConfiguration:3
2019-11-26 22:24:01 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('call_service', '{"domain": "group", "service": "set", "service_data": {"object_id": "all_scripts", "name": "all scripts", "visible": false, "entities": ["script.1573 ... (32 characters truncated) ... 0", "script.1560523511290", "script.1560505134064", "script.1564604012962", "script.1564603110142", "script.1574798449695", "script.1560532858680"]}}', 'LOCAL', '2019-11-26 21:16:00.545448', '2019-11-26 21:24:01.038260', '14f1e8c2acd446d785593981ac96121a', None)]
(Background on this error at: http://sqlalche.me/e/4xp6)
2019-11-26 22:24:01 ERROR (Recorder) [homeassistant.components.recorder] Error saving event: <Event call_service[L]: domain=group, service=set, service_data=object_id=all_scripts, name=all scripts, visible=False, entities=['script.1573079015162', 'script.1573074474530', 'script.1560523511290', 'script.1560505134064', 'script.1564604012962', 'script.1564603110142', 'script.1574798449695', 'script.1560532858680']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed`

**Comment by AaronDavidSchneider** [comment]
I think I know your issue @upwindanderl :
Your router has only 2.4Ghz and therefore only has 2 networks (main and guest) and not three.
I will create a pull request tomorrow.

Thanks for all of your information.

**Comment by mammuth** [comment]
> Your router has only 2.4Ghz and therefore only has 2 networks (main and guest) and not three.

Jep, looks like that's the issue.

> I will create a pull request tomorrow.

How do you want to tackle it? Try 3 and fallback two 2 or could we do something smarter? :thinking_face:

Btw @upwindanderl, it looks like your database is somehow broken. I would stop HA, rename the sql file in your config directory and start HA afterwards. This way a new sqlite database should be created.

Btw2: You also find your logs in the config directory in the file `home-assistant.log` :wink:

**Comment by AaronDavidSchneider** [comment]
> How do you want to tackle it? Try 3 and fallback two 2 or could we do something smarter? :thinking_face:

Simply ask how many Wifi networks there are.

**Comment by AaronDavidSchneider** [comment]
@upwindanderl:
Could you try to install my Pullrequest?
If you need help:
Just click on https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/fix_24_guest?files=1
And replace the files in your custom_component folder by those ones.

Thanks

**Comment by upwindanderl** [comment]
yeah!
thanks a lot :) ... the adaption was not sufficient right now
The wifi button is still grey
maybe this helps?! 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 460, in _get_action
    service = self.services[service_name]
KeyError: 'WLANConfiguration:3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/switch.py", line 327, in _async_fetch_update
    status = self.fritzbox_tools.connection.call_action('WLANConfiguration:3', 'GetInfo')['NewStatus']
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 489, in call_action
    action = self._get_action(service_name, action_name)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzconnection.py", line 462, in _get_action
    raise ServiceError('Unknown Service: ' + service_name)
fritzconnection.fritzconnection.ServiceError: Unknown Service: WLANConfiguration:3
2019-11-27 22:27:03 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Unable to reach bridge 192.168.178.28 ()
2019-11-27 22:27:12 ERROR (MainThread) [homeassistant.components.switch] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2019-11-27 22:27:13 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_utc_time_change.<locals>.pattern_time_change_listener(<Event time_c....042903+01:00>) at /usr/src/homeassistant/homeassistant/helpers/event.py:435
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 444, in pattern_time_change_listener
    calculate_next(now)

**Comment by upwindanderl** [comment]
@mammuth 
Hey Max.... got this info about my broken sqlite and did your suggestion on cleaning up by "removing" the old sqlite
The next HA start tooks quite a good long time but the super huge error list on my logfile is still there.... about 6MB only sqlite3.DatabaseError
Just before you mentioned it i thought this is normal

**Comment by AaronDavidSchneider** [comment]
@upwindanderl: are you sure that you used the correct branch? You need to use the files from the `fix_24_guest` branch.
Because it looks like my fix didn't apply.

**Comment by upwindanderl** [comment]
> 
> 
> @upwindanderl: are you sure that you used the correct branch? You need to use the files from the `fix_24_guest` branch.
> Because it looks like my fix didn't apply.

i guess ^^ 
i hope!
i followed your link and did a overwrite with these sources:
https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/fix_24_guest/custom_components/fritzbox_tools

especially your few hours old " switch.py" but also the other ones
i double checked by having a look on the timestamp
afterwards i did two time a restart and it's still this problem that the switch is grey

**Comment by AaronDavidSchneider** [comment]
Ok that's strange. 
Maybe we get more insight with the information from http://ip-of-fritzbox:49000/tr64desc.xml.
could you check for the snippet in the response that looks like this:
```XML
urn:dslforum-org:service:WLANConfiguration:3urn:WLANConfiguration-com:serviceId:WLANConfiguration3/upnp/control/wlanconfig3/upnp/control/wlanconfig3/wlanconfigSCPD.xml
```
you only have the same services for `WLANConfiguration:2` and `WLANConfiguration:1`, don't you?

**Comment by AaronDavidSchneider** [comment]
Hey @upwindanderl: I think I found the reason to why my fix wasn't working before. Could you try the new lines of code?

https://github.com/AaronDavidSchneider/ha-fritzbox-tools/tree/fix_24_guest/custom_components/fritzbox_tools

If they don't work, could you please parse the response from http://ip-of-fritzbox:49000/tr64desc.xml (see above).

Thanks!

**Comment by upwindanderl** [comment]
sorry for answering so late! 


your latest fix now works like charm!!! 
Perfect and thank you for helping me out with my superold FB :)
