### ISSUE TITLE
Switch turns off few seconds after turning on, guest WiFi remains active

### ISSUE THREAD

**Issue by ffidan61** [mammuth/ha-fritzbox-tools#60]
HA Version: 0.104.3
Fritzbox-tools Version: 1.5.3

First of all thank for this component. İt's nice to see how well organized you guys are. 👍

Somehow my guests WiFi switch turns back off 2-3 seconds after I turned it on in Lovelace, but guest WiFi on the Fritzbox remains active.

Thanks in advance.

**Comment by AaronDavidSchneider** [comment]
Interesting. Is there any Log record?
What other fritzbox related components do you use?
Since when do you have this error?

**Comment by ffidan61** [comment]
I'm using the device tracker component and the netmonitor. 

Which logs would help? And how to get those?
The device tracking component gives this error in the developer tools in HA:

> Error doing job: Task exception was never retrievedTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 163, in async_device_tracker_scan found_devices = await scanner.async_scan_devices() File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/usr/src/homeassistant/homeassistant/components/fritz/device_tracker.py", line 68, in scan_devices self._update_info() File "/usr/src/homeassistant/homeassistant/components/fritz/device_tracker.py", line 96, in _update_info self.last_results = self.fritz_box.get_hosts_info() File "/usr/local/lib/python3.7/site-packages/fritzconnection/fritzhosts.py", line 73, in get_hosts_info 'ip': host['NewIPAddress'], KeyError: 'NewIPAddress'

First I noticed it was around Christmas last year.

**Comment by AaronDavidSchneider** [comment]
I am sorry @ffidan61.
I don’t see the origin of your Problem. The devicetracker Problem is however unrelated.

Can you tell me which Fritzbox you use?
Does the switch toggle back to on after some time?

**Comment by ffidan61** [comment]
FB6490 Cable
İt does toogle back after approx. 1min.
Some how it only happens when switched on in Lovelace when turned on with an automation it works flawlessly. So my workround will be using automations :D

**Comment by AaronDavidSchneider** [comment]
Very strange.
I have the same setup and it works for me.
You should try to readd the integration and see if this helps.

**Comment by brenter** [comment]
I have the same issue since a couple of days. Worked fine before.
And it only happens for the Guest Wifi Switch.
It always shows off. If i press it in the UI, or even set the state manually, after a few seconds it turns off again even though guest wifi is always on. Readding the integration didnt change anything.

**Comment by mammuth** [comment]
Then the update method seems to fail. Do you see any error logs in home assistant @brenter?

**Comment by brenter** [comment]
Nope nothing in homeassistant error log

**Comment by brenter** [comment]
started to work again without me having changed anything. As suddenly as it stopped working. Not sure what is happening.

**Comment by mammuth** [comment]
Strange. Thanks for coming back for the info, though.

**Comment by mammuth** [comment]
I got this behaviour after upgrading to version 1.7.0 of this integration on my production system. I first assumed it was related to the update of `fritzconnection`.

On the first glimpse I don't see what might causing this.

**Comment by braetkuegeli** [comment]
I had same behavior:
the switch (lovelace) for the WLAN switches always (~every 30s) off despite it's on, and the switch for the guest-WLAN turns always on despite it's off.
I made a change in switch.py  FritzBoxWifiSwitch#_async_fetch_update and now it works as expected:

```
            _LOGGER.debug(f"WiFi {self._network_num} GetInfo:")
            _LOGGER.debug(wifi_info)
            self._is_on = wifi_info["NewEnable"] is True
```
