### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by FrancYescO** [mammuth/ha-fritzbox-tools#69]
<img width="505" alt="immagine" src="https://user-images.githubusercontent.com/4574593/74477165-12341a00-4eab-11ea-902b-fd5fcf946769.png">
After inserting correct values (otherwise it gives me check credentials) .. where to check logs ?

Installed via HACS v1.7.1
FRITZ!Box 7590 FRITZ!OS 7.13

**Comment by mammuth** [comment]
You will find your Home Assistant logs at `Sidebar > Developer Tools > Logs`

**Comment by FrancYescO** [comment]
The exception was
```Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 160, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 89, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/fritzbox_tools/config_flow.py", line 99, in async_step_start_config
    device_list=None
  File "/config/custom_components/fritzbox_tools/__init__.py", line 143, in __init__
    "http://" + host, username, password
  File "/usr/local/lib/python3.7/site-packages/fritz_switch_profiles/fritz_switch_profiles.py", line 21, in __init__
    self.sid = self.login(user, password)
  File "/usr/local/lib/python3.7/site-packages/fritz_switch_profiles/fritz_switch_profiles.py", line 47, in login
    raise PermissionError('Cannot login to {} using the supplied credentials.'.format(self.url))
PermissionError: Cannot login to http://192.168.144.1 using the supplied credentials.
```

this was caused because i was not using the "LAN" user (admin) but the "WAN" credentials and looks like this was a not managed error.

simply solved using the LAN credentials

**Comment by mammuth** [comment]
Perfect, thanks.
