### ISSUE TITLE
port forwarding with port range not working

### ISSUE THREAD

**Issue by kevinkk525** [mammuth/ha-fritzbox-tools#75]
I have a port forwarding rule that forwards a range of ports (28967-28970). However the integration doesn't support that and therefore can't add the switches to control the port forwarding rules.

```
 [custom_components.fritzbox_tools.switch] Port switches could not be enabled. Check if your fritzbox is able to do port forwardings!
Traceback (most recent call last):
  File "/config/custom_components/fritzbox_tools/switch.py", line 73, in _create_port_switches
    NewPortMappingIndex=i,
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 170, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 154, in handle_response
    return self.parse_response(response, service, action_name)
  File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 197, in parse_response
    value = self.conversion_table[data_type](value)
ValueError: invalid literal for int() with base 10: '28967-28970'
```

**Comment by mammuth** [comment]
Thanks for your report!

**Comment by AaronDavidSchneider** [comment]
This is a known issue of the underlying library fritzconnection.
See https://github.com/kbr/fritzconnection/issues/35.

**Comment by kevinkk525** [comment]
oh good to know, thanks. Guess we'll just have to wait for a fix then.

**Comment by chemelli74** [comment]
This custom integration is now deprecated because is fully merged into HomeAssistant core.

I would suggest you configure the new integration and retest your issue; if still present then open a issue on HomeAssistant Core repository.

Simone
