### ISSUE TITLE
fritzbox tools are spamming my logfile

### ISSUE THREAD

**Issue by lweberru** [mammuth/ha-fritzbox-tools#77]
Hi,

the following error (and similar ones) are spamming my logfile very hard. And also it seems to not work as expected. Can you please have a look into this. I am using newest version of HA and this fritzbox tools.
```
2020-03-29 13:01:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.fritzbox_profile_laptop_jan_lan_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/fritzbox_tools/switch.py", line 541, in async_update
    await self._async_fetch_update()
  File "/config/custom_components/fritzbox_tools/switch.py", line 509, in _async_fetch_update
    await self.fritzbox_tools.async_update_profiles()
  File "/config/custom_components/fritzbox_tools/__init__.py", line 192, in async_update_profiles
    await asyncio.coroutine(self.profile_switch.fetch_devices)()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/fritz_switch_profiles/fritz_switch_profiles.py", line 106, in fetch_devices
    j = r.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
If you cant fix it soon, give me a hint to at least get rid of the spamming.

Regards
Lukas

**Comment by AaronDavidSchneider** [comment]
Hey it seems that your profile switches don’t work as expected. You can fix it by deactivating the profile switches.
Looks like some error of the underlying library...
What Fritzbox do you use?

**Comment by lweberru** [comment]
Hi,

Its a fritzbox 6591 cable (lgi) 07.13

Von meinem iPad gesendet

Am 29.03.2020 um 14:45 schrieb Aaron David Schneider <notifications@github.com>:

﻿

Hey it seems that your profile switches don’t work as expected. You can fix it by deactivating the profile switches.
Looks like some error of the underlying library...
What Fritzbox do you use?

**Comment by PeteSSMMSS** [comment]
I have the same problem

```
2020-04-15 09:33:38 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.fritzbox_profile_edens_imac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/fritzbox_tools/switch.py", line 541, in async_update
    await self._async_fetch_update()
  File "/config/custom_components/fritzbox_tools/switch.py", line 509, in _async_fetch_update
    await self.fritzbox_tools.async_update_profiles()
  File "/config/custom_components/fritzbox_tools/__init__.py", line 191, in async_update_profiles
    await asyncio.coroutine(self.profile_switch.fetch_profiles)()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/fritz_switch_profiles/fritz_switch_profiles.py", line 130, in fetch_profiles
    html = lxml.html.fromstring(r.text)
  File "/usr/local/lib/python3.7/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/lib/python3.7/site-packages/lxml/html/__init__.py", line 764, in document_fromstring
    "Document is empty")
```

FRITZ!Box 6591 Cable (kdg)

If I go to fritz.box System/Ereignisse, there are also a lot of this logs:

`Anmeldung einer App des Benutzers fritzboxtools von IP-Adresse 192.168.178.XX.`

`Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse XXXgescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.178.XX beendet. [4 Meldungen seit 15.04.20 09:37:14]`

**Comment by mammuth** [comment]
Thanks for the additional logs of the Fritzbox, @PeteSSMMSS!

**Comment by PeteSSMMSS** [comment]
thanks for your quick reply @mammuth ! hope somebody can fix that, love this integration! I have a couple of other fritzbox integrations/sensors (devices, climate, call monitor) all with separate user/password, but none of them shows this kind of errors

**Comment by Janhsen** [comment]
Same for me here with a FRITZ!Box 6591 Cable

**Comment by valvanet** [comment]
Similar Problems here with FRITZ!Box 6490 Cable (FRITZ!OS 06.52)

Same log entries on Fritzbox but a different one in HomeAssistant:
Credentials valid (tested over the web interface)

2020-07-11 20:28:39 ERROR (MainThread) [custom_components.fritzbox_tools.switch] Authorization Error: Please check the provided credentials and verify that you can log into the web interface. 
Traceback (most recent call last):
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1630, in feed     self.parser.Parse(data, 0) xml.parsers.expat.ExpatError: mismatched tag: line 1, column 174 During handling of the above exception, another exception occurred: Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 58, in raise_fritzconnection_error     root = etree.fromstring(response.content)   File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML     parser.feed(text)
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1632, in feed     self._raiseerror(v)
File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1531, in _raiseerror     raise err   File "<string>", line None xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 174
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/fritzbox_tools/switch.py", line 634, in _async_fetch_update     wifi_info = await self.hass.async_add_executor_job(lambda: self._fritzbox_tools.connection.call_action(
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run     result = self.fn(*self.args, **self.kwargs)   File "/config/custom_components/fritzbox_tools/switch.py", line 635, in <lambda>     f"WLANConfiguration:{self._network_num}", "GetInfo"   
File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/fritzconnection.py", line 207, in call_action     return self.soaper.execute(service, action_name, arguments)
File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 170, in execute     return handle_response(response)   File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 153, in handle_response     raise_fritzconnection_error(response)
File "/usr/local/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 68, in raise_fritzconnection_error     raise FritzConnectionException(msg) 
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_ACCESS_DENIED)401 UnauthorizedERR_ACCESS_DENIEDWebserver Sat, 11 Jul 2020 18:28:39 GMT

**Comment by AaronDavidSchneider** [comment]
outdated due to update of profile switches.
Feel free to open up a new issue, if there are still errors! Thanks again for reporting.
